import { PRIVILEGE_CATALOG } from '../../src/roles/privilege-catalog.constant';
import { Prisma } from '../../src/generated/prisma/client';

// Auto-generated from the central catalog — do not edit this file directly.
// To add, rename, or remove a privilege, edit privilege-catalog.constant.ts instead.
export const privileges: Prisma.PrivilegeCreateManyInput[] =
  PRIVILEGE_CATALOG.map((privilege) => ({
    key: privilege.key,
    module: privilege.module,
    action: privilege.action,
    description: privilege.description,
  }));
